ExUnit.start()

Code.require_file("support/weld_helpers/core_workbench_contracts_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_daemon_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_devtools_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_job_runtime_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_log_runtime_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_node_ir_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_platform_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_process_runtime_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_shell_core_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_store_local_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_transport_local_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_tui_framework_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_workbench_widgets_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/sites_site_local_test_helper.exs", __DIR__)
